name: Release and Build Storybook

on:
    push:
        branches:
            - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16]
        steps:
            - uses: actions/checkout@v2
              with:
                  # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
                  fetch-depth: 0
                  token: ${{ secrets.MASTER_KEY }}

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: 'Setup pnpm authorization'
              run: |
                  pnpm set @hadeeka:registry=https://npm.pkg.github.com/
                  pnpm set "//npm.pkg.github.com/:_authToken=${{ secrets.MASTER_KEY }}"

            - name: Install dependencies
              run: pnpm install

            - name: Create Release Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: pnpm release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    storybook:
        needs: release
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
                  fetch-depth: 0
                  token: ${{ secrets.GH_ACTION_TOKEN }}

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: 'Setup pnpm authorization'
              run: |
                  pnpm set @hadeeka:registry=https://npm.pkg.github.com/
                  pnpm set "//npm.pkg.github.com/:_authToken=${{ secrets.MASTER_KEY }}"

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm build

            - name: Publish Storybook
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: gh-pages # The branch the action should deploy to.
                  folder: storybook-static # The folder that the build-storybook script generates files.
                  CLEAN: true # Automatically remove deleted files from the deploy branch
